---
title: ""
author: ""
date: ""
output: 
  pdf_document: 
    fig_caption: yes
  css: SIG5_211203.css
classoption: a4paper
---

\pagenumbering{gobble}

```{r setting, include=F}
knitr::opts_chunk$set(echo = FALSE)

# Load libraries
library(rstan)
library(bayesplot)
library(ggpubr)
library(tidyverse)
library(patchwork)
library(plyr)
library(rmdformats)
library(knitr)

# Load plot function
source("functions/Plot_functions_220813.R")
```

```{r MarSep, fig.align="center", fig.dim=c(5,5)}

##### Local comparisons

### Temperature
local_environment_data <- read.csv("data/local_environment_data.csv")
local_environment_data$Condition = factor(local_environment_data$Condition, levels=c("Ambient Conditions", "Warm", "Chill", "Low light"))
local_environment_data <- local_environment_data[local_environment_data$Condition!=unique(local_environment_data$Condition)[4],]



# plot code:
g_temp <- ggplot(local_environment_data, aes(x=Time, y=Temperature, group=Condition, color=Condition)) + 
  annotate("rect", xmin = 12, xmax = 24, ymin = 0, ymax = 35, alpha = 0.3, fill = "gray50")+
  annotate("rect", xmin = 36, xmax = 39, ymin = 0, ymax = 35, alpha = 0.3, fill = "gray50")+
  #geom_point(aes(color=Condition), shape=19, size=1, alpha = 0.6, stroke = 1.2)+
  geom_line(aes(color=Condition), size= 1, alpha = 1) +
  theme_classic(7) +
  theme(legend.position = "none",
        axis.text = element_text(size = 7),
        axis.title = element_text(size = 7),
        plot.title = element_blank(),
        plot.tag = element_text(size = 7, face = "bold"))+
  scale_colour_manual(values=c("black", "orangered", "cyan3", "lavenderblush4"))+
  scale_fill_manual(values=c("black", "orangered", "cyan3", "lavenderblush4"))+
  scale_y_continuous(expand = c(0, 0), breaks=seq(0,35,5), limits = c(0, 35.5))+
  scale_x_continuous(breaks=seq(12,36,6), limits=c(11,39))+
  labs(
       #title = "Temperature", subtitle = "Multiple local treatments", 
       tag = "B", 
       x = "Time relative to initial dawn (h)", 
       y = expression(atop("Temperature",  paste("(°C)" ))))




# Load output
load("SSM_out/SSM_diff_local_out.RData")

# Visualization
glist_AhgCCA1_local <- diff_vis_local(df = result_df_AhgCCA1_local_rev, var = "AhgCCA1")
glist_AhgSIG5_local <- diff_vis_local(df = result_df_AhgSIG5_local_rev, var = "AhgSIG5")
glist_AhgBLRP_local <- diff_vis_local(df = result_df_AhgBLRP_local_rev, var = "AhgpsbD BLRP")




# Integration of all plots into a figure
glist <- c(list(g_temp), glist_AhgCCA1_local, glist_AhgSIG5_local, glist_AhgBLRP_local)

(glist[[1]] + labs(tag = "A")) + (glist[[2]] + labs(tag = "B")) +
legend_local2 + glist[[3]] +
(glist[[4]] + labs(tag = "C")) + (glist[[6]] + labs(tag = "D")) +
glist[[5]] + glist[[7]] +
plot_layout(ncol=2) +
plot_annotation(title = "Fig. 4") &
theme(plot.tag = element_text(size = 10))
```

